[auth]
enabled = true

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[auth.external.github]
enabled = true

[storage]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000 